### ISSUE TITLE
 Too many users have this username, please try another.

### ISSUE THREAD

**Issue by droopified** [NeotiDev/Discord-Discrim-Seeker#2]
would it be possible to write a "skip name" for next attempt so it doesnt run that name anymore since too many people have it?

**Comment by yagizhan49** [comment]
I guess you're talking about the DiscordAPIError, it automatically tries again whenever it OOFs, but that error is also returned when you exceeded your quota, (2 username and 1 discrim changes per day or smthing like that). So the error is probably showing up because you exceeded your limit, that's nothing the code can do.

Just wait until Discord lets you change your username again.

**Comment by droopified** [comment]
this issue seems to be that the name it is switching to is taken. even if i change my discord name manually to the first result with the same discrim gives me that in discord itself. so far the way i was able to continue is saving a list of discrims and check them 1 by 1 and hope that they havnt changed names during my cooldown since changing a name counts as 1 of your quota even if it is available or not.
